### ISSUE TITLE
[BUG] - Espacio vacío en Home

### ISSUE THREAD

**Issue by VictorPB** [UGR-Lan-Party/ulp-website#84]
### Descripción

En el home, debajo de la imagen de fondo encontramos un hueco vacío.

![SCR-20241112-sxan](https://github.com/user-attachments/assets/48441716-405f-4617-95a1-c5ef45113715)

### Pasos para Reproducción

```bash
1. Ir a la página 'Home'
2. Desplazarse hacia abajo un poco muestra debajo de la imagen un espacio vacío.
```

### Capturas de Pantalla

```bash
![DESCRIPCIÓN](ENLACE.png)
```

**Comment by puchy22** [comment]
@VictorPB por que se reabrio esta issue? En la pagina veo que el espacio que se comenta en la descripcion ya no existe.
